name: Release Stream Deck Plugin

on:
  push:
    tags:
      - 'v*'  # v1.0.0 のような形式のタグでトリガー

jobs:
  release:
    name: Create Release
    runs-on: macos-latest  # Stream Deck Distribution Tool は macOS と Windows のみサポート
    permissions:
      contents: write  # リリース作成とファイルアップロードに必要
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Build plugin
        run: bun run build
        
      - name: Verify build output
        run: |
          echo "=== Checking build output ==="
          ls -la works.nantoka.droidcam.sdPlugin/bin/
          echo "=== Plugin.js file size ==="
          wc -c works.nantoka.droidcam.sdPlugin/bin/plugin.js
          echo "=== Checking if plugin.js is executable ==="
          file works.nantoka.droidcam.sdPlugin/bin/plugin.js
        
      - name: Create release directory
        run: mkdir -p release
        
      - name: Install Elgato Stream Deck CLI
        run: bun add -g @elgato/cli
        
      - name: Validate plugin structure
        run: streamdeck validate works.nantoka.droidcam.sdPlugin
        
      - name: Package Stream Deck plugin
        run: streamdeck pack works.nantoka.droidcam.sdPlugin --force
        
      - name: Verify package output
        run: |
          echo "=== Checking packaged file ==="
          ls -la works.nantoka.droidcam.streamDeckPlugin
          echo "=== Package size ==="
          wc -c works.nantoka.droidcam.streamDeckPlugin
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: DroidCam Stream Deck Plugin ${{ github.ref_name }}
          body: |
            ## DroidCam Stream Deck Plugin ${{ github.ref_name }}
            
            ### インストール方法
            1. 下記の `works.nantoka.droidcam.streamDeckPlugin` ファイルをダウンロード
            2. ダウンロードしたファイルをダブルクリックしてStream Deckアプリにインストール
            
            ### 変更内容
            詳細は [HISTORY.md](https://github.com/nantokaworks/streamdeck-droidcam/blob/main/HISTORY.md) を参照してください。
          files: works.nantoka.droidcam.streamDeckPlugin
          draft: false
          prerelease: false